version: '3.7'

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./config/limiter.toml:/etc/searxng/limiter.toml:ro # Mount limiter.toml
    ports:
      - 8080:8080
    networks:
      - perplexica-network
    restart: unless-stopped
    environment:
      - BASE_URL=https://clownfish-app-fvz8p.ondigitalocean.app/ghcr-io-lego-4005-searxng

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        SEARXNG_API_URL: https://clownfish-app-fvz8p.ondigitalocean.app/ghcr-io-lego-4005-searxng
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - ./config/config.toml:/app/config.toml:ro # Mount config.toml
    networks:
      - perplexica-network
    restart: unless-stopped
    environment:
      - PORT=3001
      - CONFIG_PATH=/app/config.toml

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://clownfish-app-fvz8p.ondigitalocean.app/ghcr-io-lego-4005-perplexica-bac/api
        NEXT_PUBLIC_WS_URL: wss://clownfish-app-fvz8p.ondigitalocean.app/ghcr-io-lego-4005-perplexica-bac
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped
    environment:
      - PORT=3000

networks:
  perplexica-network:

volumes:
  backend-dbstore:
