services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /home/Perplexica/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=Cvvvvvvvvvvvvv
      - OPENVPN_PASSWORD=Jcccccccccccccc
      - SERVER_COUNTRIES=United States
      - SERVER_HOSTNAMES=node-us-CUSTOMIZE
      - TZ=America/Los_Angels
      - BLOCK_MALICIOUS=on 
      - BLOCK_SURVEILLANCE=on 
      - BLOCK_ADS=on
      - DOT=on
      - FIREWALL_OUTBOUND_SUBNETS=CUSTOMIZE
    networks:
      - perplexica-network
    ports:
      - 3001:3001
      - 3000:3000
      - 4000:8080
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    network_mode: 'service:gluetun'
    depends_on:
      - gluetun
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    volumes:
      - backend-dbstore:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    depends_on:
      - gluetun
      - searxng
    network_mode: 'service:gluetun'
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.70.54:3001/api
        - NEXT_PUBLIC_WS_URL=ws://192.168.70.54:3001
    image: itzcrazykns1337/perplexica-frontend:main
    depends_on:
      - gluetun
      - perplexica-backend
    network_mode: 'service:gluetun'
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
